import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

const fontInter = Inter({
  variable: "--font-primary",
  subsets: ["latin"],
});

const fontPoppins = Poppins({
  weight: ["400", "600"],
  variable: "--font-secondary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Project Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${fontInter.variable} ${fontPoppins.variable} authPage antialiased`}>
      {children}
    </body>
    </html>
  );
}
